add utilities check
warn of missing utilities (e.g. isohybrid), exit

diff --git a/debian-build b/debian-build
--- a/debian-build
+++ b/debian-build
@@ -53,13 +53,29 @@ echo "ARCHIVE HOST $ARCH_HOST"
 ARCH_PATH=$(echo $ARCH_URL | sed -e "s+https\\?://$ARCH_HOST++")
 echo "ARCHIVE PATH $ARCH_PATH"
 
-if ! which >/dev/null 7z; then
-	echo "please install '7z' file archive utility"
-	exit
+# check for presence of extra utilities
+
+MISSING=""
+if ! which >/dev/null 2>&1 m4; then
+	MISSING="$MISSING m4"
 fi
 
-if [ "$ISO" = "" ]; then
-	echo "please provide master ISO path"
+if ! which >/dev/null 2>&1 7z; then
+	MISSING="$MISSING 7z"
+fi
+
+if ! which >/dev/null 2>&1 genisoimage; then
+	MISSING="$MISSING genisoimage"
+fi
+
+if ! which >/dev/null 2>&1 isohybrid; then
+	MISSING="$MISSING isohybrid"
+fi
+
+if [ "$MISSING" != "" ]; then
+	echo
+	echo "missing utilities, please install: $MISSING"
+	echo "See package-notes."
 	exit
 fi
 
